Repository apel/grafana-dashboards, pull requests merged in 2019-11, with the labels that each got.

#24 Set variables to refresh
  dashboards/grid.json
Labels: bug

#26 Change dirac colour
  colourmapper.ini
  dashboards/grid.json
Labels: enhancement

#23 Tweak docs after following them through
  docs/IAM_setup_guide.md
Labels: documentation
