Repository apel/grafana-dashboards, pull requests merged in 2020-02, with the labels that each got.

#62 Fix projection graph
  dashboards/resource_manager.json
Labels: bug

#63 Add decimal place to pie chart percentages
  dashboards/grid.json
Labels: enhancement

#64 Move scripts and schemas to specific dirs
  schemas/iris-initialisation.sql
  schemas/iris-schema.sql
  scripts/colourmapper.ini
  scripts/colourmapper.py
Labels: enhancement

#65 Provisioning & directory info
  README.md
  provisioning/dashboards/iris.yml
  provisioning/datasources/iris.yml
Labels: documentation, enhancement
